### ISSUE TITLE
NaN Error Radius

### ISSUE THREAD

**Issue by DrYSG** [domoritz/leaflet-locatecontrol#20] opened 2013-05-08 19:26 UTC
I upgraded to Leaflet 0.6 and the latest Locate control. I am getting a new type of error. On FireFox V20, I am finding that the error radius is NaN. So I am getting errors on creating the circle:

```
var locateControl = new L.control.locate({
    position: "topleft",
    drawCircle: true
});
```

If I turn off the drawCircle: false, I do get the correct location (with the marker, and with the tooltip saying that you are within NaN of this location).

I tried this again with Chrome v26, and I am getting that I am within 1200 meters.

The really odd thing is that your demo at http://domoritz.de/leaflet-locatecontrol/demo/ does work for me in FireFox, and it also says that I am withing 1200 meters.

I am testing on a desktop machine (win7).

**Comment by domoritz** [comment] 2013-05-08 20:42
Thanks for reporting this. Since Leaflet 0.6 is not out yet, this might change. I'll wait for the final release and look into this issue then, If you have a fix for this problem, I'd be happy to merge it ;-)

The demo probably works because it is Leaflet 0.5.

**Comment by domoritz** [comment] 2013-06-16 21:19
I'll close this because I can't reproduce this with 0.5. Once 0.6 is out, we should tests whether this error occurs.

**Closed as completed by domoritz** 2013-06-16 21:19 UTC
Labels: invalid
