### ISSUE TITLE
Accuracy circle and circle marker not removed on stopLocate()...

### ISSUE THREAD

**Issue by celoftis** [domoritz/leaflet-locatecontrol#41] opened 2013-10-18 13:51 UTC
When stopLocate fires self._layer.clearLayers(); executes to remove the _circle and _circleMarker from the LayerGroup. 

On Android 4.2.2, Samsung Galaxy tab 7, I am noticing that clearLayers() does not remove the accuracy circle or circleMarker. I have to manually re-position the map for the circle and circleMarker marker to disappear (i assume a redraw or invalidate is being fired?)

I am using the leaflet 0.6.2 & latest version of the leaflet-locatecontrol as of Oct 12, '13.

**Comment by domoritz** [comment] 2013-10-19 20:04
I am not sure I understand you correctly. Could you give me the steps to reproduce the problem? Also, does this appear only in the mobile browser or also on the desktop?

**Comment by celoftis** [comment] 2013-10-20 17:00
I have only observed the problem on Android 4.2.2 using a Samsung Galaxy tab. It does not happen on Android 3.2 on a Samsung Galaxy Tab, nor have I observed the problem in a desktop browser.

I observe the problem in normal use - start following, then tap the icon the stop following, but the circle and circle marker do not disappear.

**Comment by domoritz** [comment] 2013-10-20 17:17
Thank you for your experiments. I'm afraid, that I won't be able to fix it and would assume that it is a problem with leaflet and not the plugin.

**Comment by celoftis** [comment] 2013-10-20 17:46
Ok, thanks for the update

**Comment by domoritz** [comment] 2013-10-20 19:34
Closing this for now as I can't reproduce/debug/fix this.

**Closed as completed by domoritz** 2013-10-20 19:34 UTC
