### ISSUE TITLE
setView:'once' and 'untilPan' don't work properly

### ISSUE THREAD

**Issue by Alex-ej** [domoritz/leaflet-locatecontrol#168] opened 2016-06-14 09:41 UTC
If I initialize the map with default options and lc.start, I always need to click on the control button to stop the GPS logging in order to stop the map from jumping to the position. Actually, it tries to jump to the location but never shows the current position in the center of the screen.

If I set 'once' then it does no localization at all on lc.start. 

Can you check/fix this?

**Comment by domoritz** [comment] 2016-06-15 21:41
I can look into it. Can you provide some code that I can run to reproduce it?

**Comment by Alex-ej** [comment] 2016-07-02 11:11
Do you need a full working leaflet map or just the part where I'm referencing to your plugin?

**Comment by domoritz** [comment] 2016-11-07 19:33
A full running example would be great.

**Comment by davidmann4** [comment] 2017-12-04 13:01
also having the same problem with this. on mobile the map always jumps back to the users person. 

ios even more than android. Hard to reproduce, it seems to be linked to GPS signal strength. 

https://res.bluecode.com/map/

**Comment by d89** [comment] 2018-10-13 19:16
Same problem here, "once" just never jumps to the current position.

**Comment by domoritz** [comment] 2018-10-13 20:09
Can someone who can reproduce this debug the problem?

**Comment by d89** [comment] 2018-10-13 21:30
Hey @domoritz - sorry, I was confused and it is my fault. Things work as they should 👍

**Comment by domoritz** [comment] 2018-10-13 21:35
No problem and thanks for getting back to me. Since I couldn’t reproduce the issue for two years, I’m going to close the issue.

**Closed as completed by domoritz** 2018-10-13 21:35 UTC
