### ISSUE TITLE
`following` class not removed when map is zoomed

### ISSUE THREAD

**Issue by jayenashar** [domoritz/leaflet-locatecontrol#210] opened 2018-09-02 10:05 UTC
seems to work fine when i pan, but if i zoom somewhere away from the geolocated location, the `following` class is still present in the DOM.

**Comment by domoritz** [comment] 2018-09-05 18:55
This is by design. If you think this should be changed, please respond to the issue. I'm going to close it for now but keep the discussion open.

**Closed as completed by domoritz** 2018-09-05 18:55 UTC

**Comment by jayenashar** [comment] 2018-09-05 19:15
I do think it should be changed.  Though I can't think of a good reason.  In my case I don't normally pan so if I zoom somewhere then want to come back to my location, I have to click the control twice (off and back on).

**Comment by domoritz** [comment] 2018-09-05 19:29
My thinking was that when you zoom, you are still at your location so you can just zoom out to how far you want to be.

**Comment by jayenashar** [comment] 2018-09-05 19:38
Sorry I mean instead of panning, I zoom out, then in, to where I want, so then to go back to my current location, one click is easier than zooming back out and in.

**Comment by domoritz** [comment] 2018-09-05 19:53
If you want to change this, please add an option to configure the behavior of the follow feature and send a PR.
